language: ruby
rvm: 2.2.2
sudo: false

before_install:
 - gem install hiptest-publisher
 - hiptest-publisher -c minitest.conf --test-run-id=1356 --only=tests

script:
 - bundle exec rake test

after_script:
  - hiptest-publisher -c minitest.conf --push="test/reports/TEST-*.xml" --test-run-id=1356
