language: ruby
rvm: 2.2.2
sudo: false

before_install:
 - gem install hiptest-publisher
 - hiptest-publisher -c minitest.conf --test-run-id=1356 --only=tests

script:
 - bundle exec ruby -Ilib test/project_test.rb --junit

after_script:
  - hiptest-publisher -c minitest.conf --push=report.xml --test-run-id=1356
